export enum AreaConfirmationStatus {
    CONFIRMED = "CONFIRMED",
    PENDING = "PENDING",
    REJECTED = "REJECTED"
}

export enum PriceType {
    HOUR = "HOUR",
    DAY = "DAY",
    RENT = "RENT",
    FREE = "FREE"
}

export enum Specialization {
    FILM_STUDIO = "FILM_STUDIO",
    GALLERY = "GALLERY",
    PUBLISHING_HOUSE = "PUBLISHING_HOUSE",
    BOOKSTORE = "BOOKSTORE",
    DESIGN_STUDIO = "DESIGN_STUDIO",
    CREATIVE_SPACE = "CREATIVE_SPACE",
    CINEMA = "CINEMA",
    SOUND_RECORDING_STUDIO = "SOUND_RECORDING_STUDIO",
    AR_VR_STUDIOS = "AR_VR_STUDIOS"
}
